apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ceph-test-ephemeral
  namespace: jones
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
  storageClassName: csi-cephfs-sc-ephemeral
